### ISSUE TITLE
menubar icon has the wrong color

### ISSUE THREAD

**Issue by vordenken** [Lennolium/swiftGuard#9]
## Issue description
The menubar icon is white instead of black
<img width="314" alt="Bildschirmfoto 2023-10-16 um 16 24 07" src="https://github.com/Lennolium/swiftGuard/assets/62395860/971d3a68-4ec9-41b4-8032-ea13e89a2035">

## Environment

 
- Operating System Version: macOS 14.0
- Additional Information:

## Steps to reproduce the issue

1. Look at menubar
2.  
3.  

## What is expected?
It should look like the other icons

## Additional details / screenshots
<img width="314" alt="Bildschirmfoto 2023-10-16 um 16 24 07" src="https://github.com/Lennolium/swiftGuard/assets/62395860/7c9ed319-89a5-4308-9988-8db602cc49b6">

**Comment by Lennolium** [comment]
Hey, 
Can you please tell me which version of swiftGuard you are using (v0.0.1 or 0.0.2)?
And did you install swiftGuard with its .app or .dmg file or are you running it as Python script (poetry or git clone)?

Seems like its a common issue for older Python versions. Also it can only detect if your dark mode is enabled or disabled. The different brightness states of the macOS menu bar are not detectablenpy Qt.

**Comment by vordenken** [comment]
Hey,
I'm using 0.0.2 and installed it via the .dmg file :)

**Comment by Lennolium** [comment]
Small update:

After investigating deep into the macOS/Qt framework, I could identify that a missing flag on the tray icon was the root of the bug. So it will be fixed for the next release, coming soon. 

Thanks again for submitting the issue and helping me improving swiftGuard! 😊

For other devs: 
```
# Create and configure the system tray icon.
tray_icon = QSystemTrayIcon()
tray_icon.setToolTip("swiftGuard")

# Set the app icon.
app_icon = QIcon(self.resources["app-icon"])
app_icon.setIsMask(True)  # Dark mode fix for macOS.  <------
tray_icon.setIcon(app_icon)
```
For more details check [app.py](https://github.com/Lennolium/swiftGuard/blob/main/src/swiftguard/app.py#L1027-L1048) in src.
